import { useEffect, useState } from "react";
import { ExpandedVisual } from "./ChatMedia";

/** Only clone equations generated by KaTeX after markdown sanitization. */
export function previewEquation(element: HTMLElement) {
  const equation = element.closest<HTMLElement>(".katex");
  if (!equation || window.getSelection()?.toString()) return;
  window.dispatchEvent(new CustomEvent("t3-preview-equation", { detail: { html: equation.outerHTML, display: !!equation.closest(".katex-display") } }));
}
export function EquationPreview() {
  const [preview, setPreview] = useState<{ html: string; display: boolean } | null>(null);
  useEffect(() => {
    const show = (event: Event) => setPreview((event as CustomEvent<{ html: string; display: boolean }>).detail);
    window.addEventListener("t3-preview-equation", show);
    return () => window.removeEventListener("t3-preview-equation", show);
  }, []);
  return preview ? <ExpandedVisual title="Equation preview" onClose={() => setPreview(null)}><div className={`equation-preview${preview.display ? " katex-display" : ""}`} dangerouslySetInnerHTML={{ __html: preview.html }} /><p className="subtle">Scroll horizontally for wide equations. Right-click to copy LaTeX or MathML.</p></ExpandedVisual> : null;
}
