/** Exercise occurrence navigation, persistent filters and real responsive geometry; no provider calls. */
import assert from "node:assert/strict";
import type { Page } from "playwright-core";
import { TurnItemId } from "@t3tools/contracts";
import type { HostState } from "../src/host/hostState.js";
import { publishText, type FakeTransport } from "../src/host/testing/fakeTransport.js";

export async function verifySearchPanel(page: Page, other: Page, host: HostState, client: FakeTransport, evidence: string) {
  const text = "Before far\nBefore near\nneedle CURRENT\nAfter near\nAfter far\nMore detail\nAdditional detail\nLATER needle\nLast context";
  publishText(client, "first", text, 70);
  const projection = await client.getThreadProjection("first"), seed = projection.visibleTurnItems[0]!;
  if (seed.item.type !== "assistant_message") throw new Error("Expected assistant fixture");
  const seedItem = seed.item;
  const older = Array.from({ length: 55 }, (_, i) => {
    const id = TurnItemId.make(`context-history-${i}`);
    return { ...seed, position: i - 60, sourceItemId: id, item: { ...seedItem, id, ordinal: i, text: `Earlier line\nneedle history ${i}\nLater line` } };
  });
  const commandId = TurnItemId.make("context-command");
  const command = { ...seed, position: -61, sourceItemId: commandId, item: { ...seedItem, id: commandId, type: "command_execution" as const, input: "echo result", output: "needle command\nsecond line", exitCode: 0, ordinal: 0 } };
  client.getHistory = async () => ({ snapshotSequence: 71, items: [command, ...older], nextCursor: null, hasMoreHistory: false });
  client.threadHandlers.get("first")!({ kind: "snapshot", snapshotSequence: 71, projection, historyCursor: "context-history", hasMoreHistory: true });
  const draft = page.getByRole("textbox", { name: "Message", exact: true });
  await draft.fill("Draft stays through search controls");
  await page.evaluate(`window.__searchDraftNode = document.querySelector('textarea')`);
  const otherDraft = await other.getByRole("textbox", { name: "Message", exact: true }).inputValue();
  await page.getByRole("button", { name: "Find in session", exact: true }).click();
  await page.getByRole("textbox", { name: "Find in this session", exact: true }).fill("needle");
  await page.waitForFunction(() => document.querySelector(".find-count")?.textContent === "1/58");
  const job = host.snapshot("tab-two").sessionSearch;
  assert.equal(await page.locator('.find-group-heading, .find-entry-matches, .find-ellipsis').count(), 0);
  await page.getByRole("button", { name: "Search filters", exact: true }).click();
  const filters = page.getByRole("dialog", { name: "Search filters and options", exact: true });
  await filters.getByRole("combobox", { name: "Chronological order", exact: true }).selectOption("newest");
  await filters.getByRole("combobox", { name: "Context lines", exact: true }).selectOption("0");
  await filters.getByRole("button", { name: "Done", exact: true }).click();
  await page.locator(".find-result").first().filter({ hasText: "LATER needle" }).waitFor();
  await page.locator(".find-result").nth(1).filter({ hasText: "needle CURRENT" }).click();
  await page.waitForFunction(() => document.querySelectorAll('.find-result[aria-current="true"] .find-context-line').length === 1);
  await page.getByRole("button", { name: "Search filters", exact: true }).click();
  await filters.getByRole("combobox", { name: "Context lines", exact: true }).selectOption("2");
  await page.waitForFunction(() => document.querySelectorAll('.find-result[aria-current="true"] .find-context-line').length === 5);
  assert.match(await page.locator('.find-result[aria-current="true"]').innerText(), /Before far/);
  assert.match(await page.locator('.find-result[aria-current="true"]').innerText(), /After far/);
  await filters.press("Escape");
  assert.equal(await filters.count(), 0); assert.equal(await page.locator(".session-find").count(), 1);
  assert.equal(await page.locator(".find-preview-text").first().evaluate(node => getComputedStyle(node).fontSize), await page.locator(".assistant-message .markdown").first().evaluate(node => getComputedStyle(node).fontSize));
  assert.equal(await page.locator(".find-preview-text").first().evaluate(node => getComputedStyle(node).lineHeight), await page.locator(".assistant-message .markdown").first().evaluate(node => getComputedStyle(node).lineHeight));

  const separator = page.getByRole("separator", { name: "Resize search results", exact: true });
  const bounds = await separator.boundingBox(); assert.ok(bounds);
  const before = await page.locator(".find-results").evaluate(node => node.getBoundingClientRect().height);
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2); await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2 + 80, { steps: 4 }); await page.mouse.up();
  await page.waitForFunction(previous => document.querySelector(".find-results")!.getBoundingClientRect().height > previous + 60, before);
  await separator.focus(); await separator.press("ArrowUp");
  await page.screenshot({ path: `${evidence}/search-controls-above.png` });
  await page.locator('.find-disclosure').click();
  assert.equal(await page.locator('.find-results, .find-resize').count(), 0);
  assert.ok((await page.locator('.session-find').boundingBox())!.height < 90, "Collapsed find must not keep a blank results pane");
  assert.equal(await page.locator('.session-find').evaluate(node => getComputedStyle(node).position), 'absolute');
  await page.screenshot({ path: `${evidence}/search-controls-collapsed.png` });
  await page.getByRole("button", { name: "Results beside chat", exact: true }).click();
  await page.waitForFunction(() => { const search = document.querySelector('.session-find')!.getBoundingClientRect(), chat = document.querySelector('.chat-conversation')!.getBoundingClientRect(); return search.x >= chat.right - 1 && Math.abs(search.y - chat.y) < 2; });
  assert.equal(await draft.inputValue(), "Draft stays through search controls");
  assert.equal(await page.evaluate(`window.__searchDraftNode === document.querySelector('textarea')`), true);
  assert.equal(host.snapshot("tab-two").sessionSearch, job, "Display controls must not restart the search job");
  await page.screenshot({ path: `${evidence}/search-controls-side-light.png` });
  await page.evaluate(() => {
    document.body.className = 'vscode-dark';
    const root = document.documentElement.style;
    for (const [key, value] of Object.entries({ '--vscode-editor-background': '#1f1f1f', '--vscode-editorWidget-background': '#252526', '--vscode-editor-foreground': '#eeeeee', '--vscode-input-background': '#303234', '--vscode-input-foreground': '#eeeeee', '--vscode-descriptionForeground': '#b9bfc4', '--vscode-panel-border': '#4a4e52', '--vscode-input-border': '#4a4e52', '--vscode-sideBar-background': '#252526', '--vscode-textLink-foreground': '#78c2ff', '--vscode-list-inactiveSelectionBackground': '#273e52', '--vscode-list-hoverBackground': '#303234', '--vscode-focusBorder': '#78c2ff' })) root.setProperty(key, value);
  });
  assert.equal(await page.locator('.find-preview-text').first().evaluate(node => getComputedStyle(node).color), 'rgb(238, 238, 238)');
  await page.getByRole("button", { name: "Search filters", exact: true }).click();
  await filters.getByRole('checkbox', { name: 'Figures', exact: true }).check();
  await filters.getByRole('checkbox', { name: 'Code', exact: true }).check();
  assert.equal(await filters.isVisible(), true, "Changing several filters must keep the popup open");
  await page.waitForFunction(() => document.querySelector('.find-count')?.textContent === '1/1');
  await filters.getByRole('button', { name: 'Reset filters', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.find-count')?.textContent === '1/58');
  await page.screenshot({ path: `${evidence}/search-controls-side-dark.png` });
  await filters.getByRole("button", { name: "Done", exact: true }).click();
  await page.setViewportSize({ width: 340, height: 850 });
  await page.waitForFunction(() => document.querySelector('.session-find')!.getBoundingClientRect().bottom <= document.querySelector('.chat-conversation')!.getBoundingClientRect().y + 1);
  assert.equal(host.snapshot("tab-two").searchPreferences?.layout, "side");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: `${evidence}/search-controls-narrow.png` });
  await page.setViewportSize({ width: 728, height: 850 });
  await page.waitForFunction(() => document.querySelector('.session-find')!.getBoundingClientRect().x > 300);
  await page.locator('.find-disclosure').click();
  await page.getByRole("button", { name: "Results beside chat", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.session-find')!.getBoundingClientRect().x > 300);
  await page.setViewportSize({ width: 1280, height: 850 });
  await page.getByRole("button", { name: "Results above chat", exact: true }).click();
  await page.getByRole("button", { name: "Search filters", exact: true }).click();
  await filters.getByRole("combobox", { name: "Chronological order", exact: true }).selectOption("oldest");
  await filters.getByRole("button", { name: "Done", exact: true }).click();
  await page.locator('.find-result').first().filter({ hasText: 'needle command' }).waitFor();
  await page.getByRole("button", { name: "Next results", exact: true }).click();
  await page.locator('.find-result').first().filter({ hasText: 'needle history 24' }).waitFor();
  await page.getByRole("button", { name: "Previous match", exact: true }).click();
  await page.locator('.find-result[aria-current="true"]').filter({ hasText: 'LATER needle' }).waitFor();
  await page.locator('.find-result[aria-current="true"] .find-preview-text').evaluate(node => (node as HTMLElement).style.width = '30px');
  await page.waitForFunction(() => {
    const marks = [...document.querySelectorAll('.find-result[aria-current="true"] .find-context-line mark')];
    return marks.length > 1 && marks.map(node => node.textContent).join('') === 'needle';
  });
  await page.locator('.find-result[aria-current="true"] .find-preview-text').evaluate(node => (node as HTMLElement).style.removeProperty('width'));
  assert.equal(host.snapshot("tab-three").activeThreadId, "second");
  assert.equal(await other.getByRole("textbox", { name: "Message", exact: true }).inputValue(), otherDraft);
  await page.getByRole("button", { name: "Close session search", exact: true }).click();
  await host.setSearchPreferences({ layout: "above", contextLines: 1, order: "oldest", resultsHeight: 280 });
  await page.evaluate(() => { document.body.className = 'vscode-light'; for (const key of [...document.documentElement.style]) if (key.startsWith('--vscode-')) document.documentElement.style.removeProperty(key); });
  console.log("PASS: one row per occurrence, matching chat fonts, persistent filters, floating collapse, Side toggle from collapse, 728/340px layouts, chronology/pagination and unchanged drafts.");
}
